[build]
  publish = "."
  
[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/signup"
  to = "/signup.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about_soloboss.html"
  status = 200

[[redirects]]
  from = "/pricing"
  to = "/pricing.html"
  status = 200

[[redirects]]
  from = "/help"
  to = "/help.html"
  status = 200

[[redirects]]
  from = "/legal"
  to = "/legal.html"
  status = 200

[[redirects]]
  from = "/app"
  to = "/app_hub.html"
  status = 200

[[redirects]]
  from = "/profile"
  to = "/profile.html"
  status = 200

[[redirects]]
  from = "/billing"
  to = "/billing.html"
  status = 200

[[redirects]]
  from = "/briefcase"
  to = "/briefcase.html"
  status = 200

# Agent redirects
[[redirects]]
  from = "/agent/vox"
  to = "/agent_vox.html"
  status = 200

[[redirects]]
  from = "/agent/lexi"
  to = "/agent_lexi.html"
  status = 200

[[redirects]]
  from = "/agent/roxie"
  to = "/agent_roxie.html"
  status = 200

[[redirects]]
  from = "/agent/quinn"
  to = "/agent_quinn.html"
  status = 200

[[redirects]]
  from = "/agent/vex"
  to = "/agent_vex.html"
  status = 200

[[redirects]]
  from = "/agent/lumi"
  to = "/agent_lumi.html"
  status = 200

# Catch-all redirect for SPA behavior
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self';"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000" 